package com.blaze.core.utils.util

import android.util.Log



var USER_ID = "000005"

fun globalError(place:String): String
{

    Log.e("GLOBAL_ERROR", "GLOBAL_ERROR: $place", )
    return "Something went wrong, Please try again"
}
const val PREFERENCES_NAME:String ="PREFERENCES_NAME"
const val ACCESS_TOKEN:String ="ACCESS_TOKEN"

val bankList = listOf(

    "AB Bank Ltd.",
    "Abu Dhabi Commercial Bank Ltd.",
    "American Express Banking Corporation",
    "Andhra Pragathi Grameena Bank",
    "Andhra Pradesh Grameena Vikas Bank",
    "Arunachal Pradesh Rural Bank",
    "Aryavart Bank",
    "Assam Gramin Vikash Bank",
    "Australia and New Zealand Banking Group Ltd.",
    "Axis Bank Ltd.",
    "BNP Paribas",
    "Bandhan Bank Ltd.",
    "Bangiya Gramin Vikas Bank",
    "Bank of America",
    "Bank of Bahrain & Kuwait BSC",
    "Bank of Baroda",
    "Bank of Ceylon",
    "Bank of China",
    "Bank of India",
    "Bank of Maharashtra",
    "Bank of Nova Scotia",
    "Barclays Bank Plc.",
    "Capital Small Finance Bank Limited",
    "Canara Bank",
    "Central Bank of India",
    "Chaitanya Godavari Grameena Bank",
    "Chhattisgarh Rajya Gramin Bank",
    "Citibank N.A.",
    "Cooperatieve Rabobank U.A.",
    "Credit Agricole Corporate & Investment Bank",
    "Credit Suisse A.G",
    "CSB Bank Ltd.",
    "CTBC Bank Co., Ltd.",
    "Dakshin Bihar Gramin Bank",
    "DCB Bank Ltd.",
    "Deutsche Bank",
    "Dhanlaxmi Bank Ltd.",
    "Ellaquai Dehati Bank",
    "Emirates Bank NBD",
    "ESAF Small Finance Bank Limited",
    "Equitas Small Finance Bank Limited",
    "Federal Bank Ltd.",
    "Fincare Small Finance Bank Limited",
    "First Abu Dhabi Bank PJSC",
    "FirstRand Bank Ltd",
    "HDFC Bank Ltd",
    "HSBC Ltd",
    "ICICI Bank Ltd.",
    "IDBI Bank Ltd.",
    "IDFC First Bank Ltd.",
    "IFSC",
    "Indian Bank",
    "Indian Overseas Bank",
    "Induslnd Bank Ltd",
    "J.P. Morgan Chase Bank N.A.",
    "Jammu & Kashmir Bank Ltd.",
    "Jana Small Finance Bank Limited",
    "Jharkhand Rajya Gramin Bank",
    "Karnataka Bank Ltd.",
    "Karnataka Gramin Bank",
    "Karnataka Vikas Grameena Bank",
    "Karur Vysya Bank Ltd.",
    "Kerala Gramin Bank",
    "Kotak Mahindra Bank Ltd",
    "Kookmin Bank",
    "Krung Thai Bank Public Co. Ltd.",
    "Madhya Pradesh Gramin Bank",
    "Madhyanchal Gramin Bank",
    "Maharashtra Gramin Bank",
    "Manipur Rural Bank",
    "Mashreq Bank PSC",
    "Meghalaya Rural Bank",
    "Mizoram Rural Bank",
    "MUFG Bank, Ltd.",
    "Nagaland Rural Bank",
    "Nainital Bank Ltd.",
    "North East Small Finance Bank Limited",
    "Odisha Gramya Bank",
    "Paschim Banga Gramin Bank",
    "Paytm Payments Bank Limited",
    "Prathama UP Gramin Bank",
    "Punjab & Sind Bank",
    "Punjab National Bank",
    "Qatar National Bank (Q.P.S.C.)",
    "RBL Bank Ltd.",
    "Sberbank",
    "SBM Bank (India) Limited",
    "Shinhan Bank",
    "Saurashtra Gramin Bank",
    "Shivalik Small Finance Bank Limited",
    "Suryoday Small Finance Bank Limited",
    "Tamil Nadu Grama Bank",
    "Tamilnad Mercantile Bank Ltd.",
    "Telangana Grameena Bank",
    "Tripura Gramin Bank",
    "UCO Bank",
    "Ujjivan Small Finance Bank Limited",
    "Utkarsh Small Finance Bank Limited",
    "Utkal Grameen bank",
    "Uttar Bihar Gramin Bank",
    "Uttarakhand Gramin Bank",
    "Uttarabanga Kshetriya Gramin Bank",
    "United Overseas Bank Ltd",
    "Unity Small Finance Bank Limited",
    "Vidharbha Konkan Gramin Bank",
    "YES Bank Ltd.",
    "DBS Bank India Limited",
    "Deutsche Bank",
    "Doha Bank Q.P.S.C",
    "Industrial & Commercial Bank of China Ltd.",
    "Industrial Bank of Korea",
    "JSC VTB Bank",
    "KEB Hana Bank",
    "Kookmin Bank",
    "Krung Thai Bank Public Co. Ltd.",
    "Mashreq Bank PSC",
    "Mizuho Bank Ltd.",
    "MUFG Bank, Ltd.",
    "NatWest Markets Plc",
    "PT Bank Maybank Indonesia TBK",
    "Sberbank",
    "SBM Bank (India) Limited",
    "Shinhan Bank",
    "Societe Generale",
    "Sonali Bank Ltd.",
    "Standard Chartered Bank",
    "Sumitomo Mitsui Banking Corporation",
)

val stateList = listOf(
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
)

